# Generated by Django 5.1.15 on 2026-09-15 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64, verbose_name='Устройство')),
                ('endpoint', models.URLField(max_length=1000, unique=True, verbose_name='Адрес пуш-сервиса')),
                ('p256dh', models.CharField(max_length=200, verbose_name='Ключ p256dh')),
                ('auth', models.CharField(max_length=100, verbose_name='Ключ auth')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='Браузер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Подписан')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя доставка')),
                ('fail_count', models.PositiveSmallIntegerField(default=0, verbose_name='Ошибок подряд')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Push-подписка',
                'verbose_name_plural': 'Push-подписки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32, verbose_name='Событие')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('body', models.CharField(blank=True, max_length=300, verbose_name='Текст')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Код ответа')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кому')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='push.pushsubscription', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Запись журнала пушей',
                'verbose_name_plural': 'Журнал пушей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='pushsubscription',
            constraint=models.UniqueConstraint(fields=('user', 'device_id'), name='one_subscription_per_device'),
        ),
    ]
