# Generated by Django 5.1.15 on 2026-09-15 19:57

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('name', models.CharField(max_length=40, verbose_name='Имя')),
                ('invite_code', models.CharField(editable=False, help_text='Входит в ссылку-приглашение. Перевыпуск делает старую ссылку недействительной.', max_length=8, unique=True, verbose_name='Код приглашения')),
                ('timezone', models.CharField(default='Europe/Moscow', help_text='Приходит с устройства. По нему считаются границы недели и месяца в счёте.', max_length=64, validators=[accounts.models.validate_timezone], verbose_name='Часовой пояс')),
                ('notify_reminders', models.BooleanField(default=True, verbose_name='Пуши-напоминания')),
                ('notify_friends', models.BooleanField(default=True, verbose_name='Пуши о друзьях')),
                ('email_verified', models.BooleanField(default=False, help_text='Задел на будущее: писем пока нет, подтверждать нечем.', verbose_name='Почта подтверждена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Доступ в админку')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Регистрация')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
