# Generated by Django 5.1.15 on 2026-09-15 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_label', models.CharField(max_length=20, verbose_name='Подпись слева')),
                ('right_label', models.CharField(max_length=20, verbose_name='Подпись справа')),
                ('pair_key', models.CharField(editable=False, max_length=41, verbose_name='Пара')),
                ('state', models.CharField(choices=[('none', 'Никто не ждёт'), ('left', 'Ждут левого'), ('right', 'Ждут правого')], default='none', max_length=5, verbose_name='Положение')),
                ('version', models.PositiveIntegerField(default=0, help_text='Растёт на каждый щелчок. По ней ловится одновременное нажатие с двух телефонов.', verbose_name='Версия')),
                ('reminder_minutes', models.PositiveSmallIntegerField(choices=[(0, 'Не напоминать'), (15, '15'), (30, '30'), (60, '60')], default=15, verbose_name='Напоминать каждые, мин')),
                ('last_action_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний щелчок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='В архиве с')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('last_action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('left_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Слева')),
                ('right_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Справа')),
            ],
            options={
                'verbose_name': 'Таймер',
                'verbose_name_plural': 'Таймеры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='Начало')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность, с')),
                ('end_reason', models.CharField(blank=True, choices=[('stopped', 'Сняли'), ('switched', 'Переключили на другого'), ('undone', 'Отменено'), ('auto_closed', 'Закрыто автоматически'), ('archived', 'Таймер в архиве'), ('admin', 'Закрыл администратор')], max_length=16, verbose_name='Причина')),
                ('counts', models.BooleanField(default=True, help_text='Отменённые и закрытые автоматически в счёт не идут. Здесь администратор разбирает спор.', verbose_name='Идёт в счёт')),
                ('last_reminder_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее напоминание')),
                ('ended_by', models.ForeignKey(blank=True, help_text='Пусто — закрыла система или администратор.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Снял')),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Включил')),
                ('timer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waits', to='timers.timer', verbose_name='Таймер')),
                ('waited_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кого ждали')),
                ('waiter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто ждал')),
            ],
            options={
                'verbose_name': 'Ожидание',
                'verbose_name_plural': 'Ожидания',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='timer',
            name='last_closed_wait',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='timers.wait'),
        ),
        migrations.AddField(
            model_name='timer',
            name='last_opened_wait',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='timers.wait'),
        ),
        migrations.AddIndex(
            model_name='wait',
            index=models.Index(fields=['timer', '-started_at'], name='timers_wait_timer_i_e5d21a_idx'),
        ),
        migrations.AddConstraint(
            model_name='wait',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('timer',), name='one_open_wait_per_timer'),
        ),
        migrations.AddConstraint(
            model_name='timer',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('pair_key',), name='one_active_timer_per_pair'),
        ),
    ]
