# Generated by Django 5.1.15 on 2026-09-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_close_hours', models.PositiveSmallIntegerField(default=12, help_text='Забытое ожидание закрывается само и в счёт не идёт.', verbose_name='Автозакрытие через, ч')),
                ('undo_seconds', models.PositiveSmallIntegerField(default=10, verbose_name='Отменить можно в течение, с')),
                ('poll_interval_seconds', models.PositiveSmallIntegerField(default=5, help_text='Как часто открытое приложение спрашивает сервер о положении тумблера.', verbose_name='Опрос таймера, с')),
                ('push_started_title', models.CharField(default='⏳ {waiter} ждёт', help_text='Подстановки: {waiter} — кто ждёт, {waited_for} — кого ждут, {actor} — кто щёлкнул, {since} — время начала, {duration} — сколько длилось, {prev_waiter}, {prev_waited_for}, {prev_duration} — прошлое ожидание при смене стороны, {name} — имя друга, {hours} — часы автозакрытия.', max_length=120, verbose_name='Началось: заголовок')),
                ('push_started_body', models.CharField(default='Кого: {waited_for} · с {since} · включил(а) {actor}', help_text='Подстановки: {waiter} — кто ждёт, {waited_for} — кого ждут, {actor} — кто щёлкнул, {since} — время начала, {duration} — сколько длилось, {prev_waiter}, {prev_waited_for}, {prev_duration} — прошлое ожидание при смене стороны, {name} — имя друга, {hours} — часы автозакрытия.', max_length=200, verbose_name='Началось: текст')),
                ('push_switched_title', models.CharField(default='🔁 Теперь ждёт {waiter}', help_text='Подстановки: {waiter} — кто ждёт, {waited_for} — кого ждут, {actor} — кто щёлкнул, {since} — время начала, {duration} — сколько длилось, {prev_waiter}, {prev_waited_for}, {prev_duration} — прошлое ожидание при смене стороны, {name} — имя друга, {hours} — часы автозакрытия.', max_length=120, verbose_name='Сменили сторону: заголовок')),
                ('push_switched_body', models.CharField(default='Кого: {waited_for} · до этого {prev_waiter} ждал(а) {prev_duration}', help_text='Подстановки: {waiter} — кто ждёт, {waited_for} — кого ждут, {actor} — кто щёлкнул, {since} — время начала, {duration} — сколько длилось, {prev_waiter}, {prev_waited_for}, {prev_duration} — прошлое ожидание при смене стороны, {name} — имя друга, {hours} — часы автозакрытия.', max_length=200, verbose_name='Сменили сторону: текст')),
                ('push_stopped_title', models.CharField(default='🎉 Дождались', help_text='Подстановки: {waiter} — кто ждёт, {waited_for} — кого ждут, {actor} — кто щёлкнул, {since} — время начала, {duration} — сколько длилось, {prev_waiter}, {prev_waited_for}, {prev_duration} — прошлое ожидание при смене стороны, {name} — имя друга, {hours} — часы автозакрытия.', max_length=120, verbose_name='Сняли: заголовок')),
                ('push_stopped_body', models.CharField(default='{waited_for} опоздал(а) на {duration}', help_text='Подстановки: {waiter} — кто ждёт, {waited_for} — кого ждут, {actor} — кто щёлкнул, {since} — время начала, {duration} — сколько длилось, {prev_waiter}, {prev_waited_for}, {prev_duration} — прошлое ожидание при смене стороны, {name} — имя друга, {hours} — часы автозакрытия.', max_length=200, verbose_name='Сняли: текст')),
                ('push_undone_title', models.CharField(default='↩️ Отменено', help_text='Подстановки: {waiter} — кто ждёт, {waited_for} — кого ждут, {actor} — кто щёлкнул, {since} — время начала, {duration} — сколько длилось, {prev_waiter}, {prev_waited_for}, {prev_duration} — прошлое ожидание при смене стороны, {name} — имя друга, {hours} — часы автозакрытия.', max_length=120, verbose_name='Отмена: заголовок')),
                ('push_undone_body', models.CharField(default='{actor} отменил(а) последний щелчок', help_text='Подстановки: {waiter} — кто ждёт, {waited_for} — кого ждут, {actor} — кто щёлкнул, {since} — время начала, {duration} — сколько длилось, {prev_waiter}, {prev_waited_for}, {prev_duration} — прошлое ожидание при смене стороны, {name} — имя друга, {hours} — часы автозакрытия.', max_length=200, verbose_name='Отмена: текст')),
                ('push_reminder_title', models.CharField(default='⏰ {waiter} ждёт уже {duration}', help_text='Подстановки: {waiter} — кто ждёт, {waited_for} — кого ждут, {actor} — кто щёлкнул, {since} — время начала, {duration} — сколько длилось, {prev_waiter}, {prev_waited_for}, {prev_duration} — прошлое ожидание при смене стороны, {name} — имя друга, {hours} — часы автозакрытия.', max_length=120, verbose_name='Напоминание: заголовок')),
                ('push_reminder_body', models.CharField(default='С {since}', help_text='Подстановки: {waiter} — кто ждёт, {waited_for} — кого ждут, {actor} — кто щёлкнул, {since} — время начала, {duration} — сколько длилось, {prev_waiter}, {prev_waited_for}, {prev_duration} — прошлое ожидание при смене стороны, {name} — имя друга, {hours} — часы автозакрытия.', max_length=200, verbose_name='Напоминание: текст')),
                ('push_auto_closed_title', models.CharField(default='Ожидание закрыто автоматически', help_text='Подстановки: {waiter} — кто ждёт, {waited_for} — кого ждут, {actor} — кто щёлкнул, {since} — время начала, {duration} — сколько длилось, {prev_waiter}, {prev_waited_for}, {prev_duration} — прошлое ожидание при смене стороны, {name} — имя друга, {hours} — часы автозакрытия.', max_length=120, verbose_name='Автозакрытие: заголовок')),
                ('push_auto_closed_body', models.CharField(default='Таймер простоял больше {hours} ч — в счёт не идёт', help_text='Подстановки: {waiter} — кто ждёт, {waited_for} — кого ждут, {actor} — кто щёлкнул, {since} — время начала, {duration} — сколько длилось, {prev_waiter}, {prev_waited_for}, {prev_duration} — прошлое ожидание при смене стороны, {name} — имя друга, {hours} — часы автозакрытия.', max_length=200, verbose_name='Автозакрытие: текст')),
                ('push_friend_request_title', models.CharField(default='👋 {name} хочет добавить тебя в друзья', help_text='Подстановки: {waiter} — кто ждёт, {waited_for} — кого ждут, {actor} — кто щёлкнул, {since} — время начала, {duration} — сколько длилось, {prev_waiter}, {prev_waited_for}, {prev_duration} — прошлое ожидание при смене стороны, {name} — имя друга, {hours} — часы автозакрытия.', max_length=120, verbose_name='Заявка в друзья: заголовок')),
                ('push_friend_added_title', models.CharField(default='🤝 {name} теперь в друзьях', help_text='Подстановки: {waiter} — кто ждёт, {waited_for} — кого ждут, {actor} — кто щёлкнул, {since} — время начала, {duration} — сколько длилось, {prev_waiter}, {prev_waited_for}, {prev_duration} — прошлое ожидание при смене стороны, {name} — имя друга, {hours} — часы автозакрытия.', max_length=120, verbose_name='Новый друг: заголовок')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
